# Generated by Django 2.2.6 on 2019-10-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191019_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='csv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='api.UploadedCSV'),
        ),
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cached/'),
        ),
    ]
